#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Device_Common

#include "Basic.hpp"

#include "EWeaponViewName_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Device_Common.ABP_Device_Common_C
// 0x1F80 (0x2690 - 0x0710)
class UABP_Device_Common_C : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0710(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0718(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x0750(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x0778(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x07A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x07C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x07F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x0818(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x0840(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x0868(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x0890(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x08B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x08E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x0908(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x0930(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x0958(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x0980(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x09A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x09D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x09F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x0A20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x0A48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x0A70(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x0A98(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x0B70(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x0BA8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x0C80(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x0CB8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x0D90(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0DC8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x0EA0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0ED8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x0FB0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0FE8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x10C0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x10F8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x11D0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1208(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x12E0(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x1318(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x1350(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x1428(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x1460(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x15F8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x1630(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x1658(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x1680(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x16A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x16D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x16F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x1720(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x1748(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x1770(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x1798(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x17C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x17E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x1810(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x1838(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x1860(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x1888(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x18B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x18D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x1900(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1928(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x1A00(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1A38(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x1B10(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x1B48(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x1C20(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x1C58(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x1D30(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1D68(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x1E40(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1E78(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x1F50(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x1F88(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x2060(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x2098(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x2170(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x21A8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x2280(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x22B8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x22F0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x2488(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x24C0(0x0198)()
	class ATsBaseCharacter_C*                     角色蓝图;                                          // 0x2658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          Weapon_Fire;                                       // 0x2660(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2661[0x3];                                     // 0x2661(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BlendSpacePriority;                                // 0x2664(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          武器是否在背后;                                    // 0x2668(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsUI;                                              // 0x2669(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_266A[0x2];                                     // 0x266A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         open_delay;                                        // 0x266C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delta_Time;                                        // 0x2670(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          主动关闭武器;                                      // 0x2674(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2675[0x3];                                     // 0x2675(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         武器变化所需突破等级;                              // 0x2678(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         当前武器突破等级;                                  // 0x267C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsUiSceneRoleActor_C*                  UI界面组件;                                        // 0x2680(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EWeaponViewName                               UI界面;                                            // 0x2688(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          是否正在播放隐藏特效;                              // 0x2689(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_Device_Common(int32 EntryPoint);
	void CustomEvent();
	void Set_Open_Delay();
	void Clear_Open_Delay();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_2739CE434DBE2083A39FD69B495EB3F2();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintInitializeAnimation();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_E7FA0AEA4F4D9515AB5BF5AC37FD3ECF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_39E6A5094AB60E03BE2089B0D0887B00();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_F3B7B59B414C0E84144368B72062FB09();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_02EBA3A24EC79133BF3F66847E091ABF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_AF95079347D05829D2D25CAA047A1BA4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_650FE42B4AF795C762BB629A58D6D6F3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_179FC3464D4423EC0D9F40BD5EB39C4A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_221B77704AC52D156BA19CA86207F990();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_293259C743DE0A8F263870B4C29BAA3A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_0384BD3F4874F7BD9189C78138933669();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_8475FEA042D7FFBC5FAC35A7100F5BAA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_4C21884D46658354CD8FA491AB22C799();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_D4A72CC8490E8FBF64E54F955CA235E6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_9B68E29F49854555551F8F9B640BC309();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_ECC111D047D595675620C381CD364F46();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_8A2185A841A6505A705C1495FA24D054();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_56A4CFBB4212CCC969B0F1A9C778E0B5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_4B9697574747B66C9A2ADCBE0587698F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_DA0A1C8845A28BA88991BCAAA1324C83();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_1294B2C4411BA21C085A62B6B010F013();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_D89A6FCA4FF2DAAA1CB2069005BF68E4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_B4ACD33441820EAD393E08ADF51E225B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_5ECEA32A4BDD5F2AF07D60BCD9E35B43();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_721E50794DDB9A79D4100EAB7E35F299();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_90D0EFAA41EA7FEDDC95AE936D982F81();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_F5DA0AB14BAE650CC9429A95FE081CF9();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_A3D57B3647D01CAB257E349D1291CC9A();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_75C781B3411C24D24B7D5FAF66DFA385();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Device_Common_AnimGraphNode_TransitionResult_496F3339419C67DBA9B833A822499DED();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Device_Common_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Device_Common_C")
	}
	static class UABP_Device_Common_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Device_Common_C>();
	}
};
DUMPER7_ASSERTS_UABP_Device_Common_C;

}

