#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_SwordScabbarcdCommon

#include "Basic.hpp"

#include "EWeaponViewName_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_SwordScabbarcdCommon.ABP_SwordScabbarcdCommon_C
// 0x1F80 (0x2690 - 0x0710)
class UABP_SwordScabbarcdCommon_C : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0710(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0718(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x0750(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x0778(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x07A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x07C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x07F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x0818(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x0840(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x0868(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x0890(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x08B8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x08E0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x0908(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x0930(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x0958(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x0980(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x09A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x09D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x09F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x0A20(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x0A48(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x0A70(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_17;                   // 0x0A98(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x0B70(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x0BA8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x0C80(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x0CB8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x0D90(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0DC8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x0EA0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0ED8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x0FB0(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0FE8(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x10C0(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x10F8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x1130(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x1208(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1240(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x1318(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x1350(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x1428(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x1460(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x15F8(0x0038)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x1630(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x1658(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x1680(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x16A8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x16D0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x16F8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x1720(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x1748(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x1770(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x1798(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x17C0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x17E8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x1810(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x1838(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x1860(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x1888(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x18B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x18D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x1900(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x1928(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x1A00(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1A38(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x1B10(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x1B48(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x1C20(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x1C58(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x1D30(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1D68(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x1E40(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1E78(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x1F50(0x0038)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x1F88(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x1FC0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x2098(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x20D0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x21A8(0x0038)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x21E0(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x22B8(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x22F0(0x0198)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x2488(0x0038)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x24C0(0x0198)()
	class ATsBaseCharacter_C*                     角色蓝图;                                          // 0x2658(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          WeaponOpen;                                        // 0x2660(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2661[0x3];                                     // 0x2661(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Open_Delay;                                        // 0x2664(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delta_Time;                                        // 0x2668(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          主动关闭武器;                                      // 0x266C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          武器在背后;                                        // 0x266D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Weapon_Open;                                       // 0x266E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsUI;                                              // 0x266F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	int32                                         武器突破等级;                                      // 0x2670(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         当前武器突破等级;                                  // 0x2674(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsUiSceneRoleActor_C*                  UI界面组件;                                        // 0x2678(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EWeaponViewName                               UI界面;                                            // 0x2680(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          是否正在播放隐藏特效;                              // 0x2681(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_ABP_SwordScabbarcdCommon(int32 EntryPoint);
	void Set_Open_Delay();
	void Clear_Open_Delay();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintInitializeAnimation();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0B83C93C4704BD56331EC790C125D684();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_60E48CAF40555926DE89C683DAB10735();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0912173A4151467FF8EA35A919EA669B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_BB2EB9A94C64021CEE07D9890242972D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_5E35E85944D11EB2E66E959A3D1B7736();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_BA0F8FE8454D662D6D3A159E338D4192();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_E060EB0545B3DC9906CF0988CB31CA5E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_C5D9C39D47564CFCA30F48848C801924();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_3B14DCD949F0D28682EEF3AF215B7C88();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0C8605904D1B20A921689987444DA0D0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_22251D08423281B2C96078BA3493D5F8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_73D412DE47BB2CC6C291A5BFBCE9A58F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_28958A5646EAA30D586DA2A3B2219E96();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_F2BC63A7446D4AADB29E8093E01230E7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_1D0051744B301420431041B80A871603();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_B656CD4C48A0FB2CD708C4B641023232();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_948277A0457037E51751EF80F57ECE0E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_861469E64CA68F604289A29F52957779();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_BF44640D412106701BE7818C40EC8836();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_4DC7BAB44412E7F9CB0FBB86EC77561E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_CE8439D84D1DBE11E2AF99944D23858E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_3C4EAFD6401882863A283AA35F8C0836();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_F1566B304355AC27F7B22FA8C6FE2660();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_EC01249D4172D395D5B8BDA0ABB12C8E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_5564B3AC47DA0EDCCAF082847FD13B53();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_SwordScabbarcdCommon_AnimGraphNode_TransitionResult_0359E2234EBDBEF31CCEB0970132CFA1();
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_SwordScabbarcdCommon_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_SwordScabbarcdCommon_C")
	}
	static class UABP_SwordScabbarcdCommon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_SwordScabbarcdCommon_C>();
	}
};
DUMPER7_ASSERTS_UABP_SwordScabbarcdCommon_C;

}

