#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIC_ME1JiancuxiongMd00401

#include "Basic.hpp"

#include "SHitInformation_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function AIC_ME1JiancuxiongMd00401.AIC_ME1JiancuxiongMd00401_C.ExecuteUbergraph_AIC_ME1JiancuxiongMd00401
// 0x0A30 (0x0A30 - 0x0000)
struct AIC_ME1JiancuxiongMd00401_C_ExecuteUbergraph_AIC_ME1JiancuxiongMd00401 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool bContent)>                K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0028)(ZeroConstructor)
	TDelegate<void(int32 对策事件ID, const struct FSHitInformation& 受击数据)> K2Node_CreateDelegate_OutputDelegate_1; // 0x0030(0x0028)(ZeroConstructor)
	bool                                          K2Node_CustomEvent_bContent;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UKuroBooleanEventBinder*                CallFunc___AIC___ReturnValue;                      // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UBP_EventManager_C*                     CallFunc______________;                            // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATsBaseCharacter_C*                     K2Node_DynamicCast_AsTs_Base_Character;            // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_CustomEvent_____ID;                         // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSHitInformation                       K2Node_CustomEvent_____;                           // 0x0088(0x08E0)(ContainsInstancedReference, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_ObjectToText_ReturnValue;            // 0x0968(0x0018)()
	bool                                          CallFunc_BeginSkill_ReturnValue;                   // 0x0980(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_981[0x7];                                      // 0x0981(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0988(0x0040)(HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x09C8(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0A08(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0A18(0x0018)()
};
DUMPER7_ASSERTS_AIC_ME1JiancuxiongMd00401_C_ExecuteUbergraph_AIC_ME1JiancuxiongMd00401;

// Function AIC_ME1JiancuxiongMd00401.AIC_ME1JiancuxiongMd00401_C.当触发对策事件时_事件_0
// 0x08E8 (0x08E8 - 0x0000)
struct AIC_ME1JiancuxiongMd00401_C_当触发对策事件时_事件_0 final
{
public:
	int32                                         对策事件ID;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSHitInformation                       受击数据;                                          // 0x0008(0x08E0)(BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_AIC_ME1JiancuxiongMd00401_C_当触发对策事件时_事件_0;

// Function AIC_ME1JiancuxiongMd00401.AIC_ME1JiancuxiongMd00401_C.狂暴
// 0x0001 (0x0001 - 0x0000)
struct AIC_ME1JiancuxiongMd00401_C_狂暴 final
{
public:
	bool                                          bContent;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_AIC_ME1JiancuxiongMd00401_C_狂暴;

}

