#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_3DTextAdaptSize

#include "Basic.hpp"

#include "BP_3DTextAdaptSize_classes.hpp"
#include "BP_3DTextAdaptSize_parameters.hpp"


namespace SDK
{

// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.ExecuteUbergraph_BP_3DTextAdaptSize
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_3DTextAdaptSize_C::ExecuteUbergraph_BP_3DTextAdaptSize(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "ExecuteUbergraph_BP_3DTextAdaptSize");

	Params::BP_3DTextAdaptSize_C_ExecuteUbergraph_BP_3DTextAdaptSize Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_3DTextAdaptSize_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "ReceiveTick");

	Params::BP_3DTextAdaptSize_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_3DTextAdaptSize_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.RefreshOriginalInfo
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_3DTextAdaptSize_C::RefreshOriginalInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "RefreshOriginalInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.CalculatePower
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   FontSize                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  Power                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_3DTextAdaptSize_C::CalculatePower(float FontSize, float* Power)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "CalculatePower");

	Params::BP_3DTextAdaptSize_C_CalculatePower Parms{};

	Parms.FontSize = FontSize;

	UObject::ProcessEvent(Func, &Parms);

	if (Power != nullptr)
		*Power = Parms.Power;
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.CalculateTargetDistance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   FontSize                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 TargetDistance_0                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_3DTextAdaptSize_C::CalculateTargetDistance(float FontSize, double* TargetDistance_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "CalculateTargetDistance");

	Params::BP_3DTextAdaptSize_C_CalculateTargetDistance Parms{};

	Parms.FontSize = FontSize;

	UObject::ProcessEvent(Func, &Parms);

	if (TargetDistance_0 != nullptr)
		*TargetDistance_0 = Parms.TargetDistance_0;
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.AdjustTextSize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ToAdjustSize                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_3DTextAdaptSize_C::AdjustTextSize(float ToAdjustSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "AdjustTextSize");

	Params::BP_3DTextAdaptSize_C_AdjustTextSize Parms{};

	Parms.ToAdjustSize = ToAdjustSize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_3DTextAdaptSize.BP_3DTextAdaptSize_C.GetAppropriateScale
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float*                                  Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_3DTextAdaptSize_C::GetAppropriateScale(float* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_3DTextAdaptSize_C", "GetAppropriateScale");

	Params::BP_3DTextAdaptSize_C_GetAppropriateScale Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}

}

