#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BaseVehicle_Seq_V2

#include "Basic.hpp"

#include "BP_BaseVehicle_Seq_V2_classes.hpp"
#include "BP_BaseVehicle_Seq_V2_parameters.hpp"


namespace SDK
{

// Function BP_BaseVehicle_Seq_V2.BP_BaseVehicle_Seq_V2_C.ExecuteUbergraph_BP_BaseVehicle_Seq_V2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseVehicle_Seq_V2_C::ExecuteUbergraph_BP_BaseVehicle_Seq_V2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVehicle_Seq_V2_C", "ExecuteUbergraph_BP_BaseVehicle_Seq_V2");

	Params::BP_BaseVehicle_Seq_V2_C_ExecuteUbergraph_BP_BaseVehicle_Seq_V2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseVehicle_Seq_V2.BP_BaseVehicle_Seq_V2_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseVehicle_Seq_V2_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVehicle_Seq_V2_C", "ReceiveTick");

	Params::BP_BaseVehicle_Seq_V2_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BaseVehicle_Seq_V2.BP_BaseVehicle_Seq_V2_C.GetFinalSpeed
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_BaseVehicle_Seq_V2_C::GetFinalSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVehicle_Seq_V2_C", "GetFinalSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BaseVehicle_Seq_V2.BP_BaseVehicle_Seq_V2_C.GetSeqBindingTag
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName*                            Tag                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BaseVehicle_Seq_V2_C::GetSeqBindingTag(class FName* Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BaseVehicle_Seq_V2_C", "GetSeqBindingTag");

	Params::BP_BaseVehicle_Seq_V2_C_GetSeqBindingTag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Tag != nullptr)
		*Tag = Parms.Tag;
}

}

