#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cloud_None

#include "Basic.hpp"

#include "BP_Cloud_None_classes.hpp"
#include "BP_Cloud_None_parameters.hpp"


namespace SDK
{

// Function BP_Cloud_None.BP_Cloud_None_C.ExecuteUbergraph_BP_Cloud_None
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Cloud_None_C::ExecuteUbergraph_BP_Cloud_None(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cloud_None_C", "ExecuteUbergraph_BP_Cloud_None");

	Params::BP_Cloud_None_C_ExecuteUbergraph_BP_Cloud_None Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Cloud_None.BP_Cloud_None_C.EditorTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Cloud_None_C::EditorTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cloud_None_C", "EditorTick");

	Params::BP_Cloud_None_C_EditorTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Cloud_None.BP_Cloud_None_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Cloud_None_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cloud_None_C", "ReceiveTick");

	Params::BP_Cloud_None_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Cloud_None.BP_Cloud_None_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Cloud_None_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cloud_None_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Cloud_None.BP_Cloud_None_C.Active
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInstantHide_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Cloud_None_C::Active(bool bInstantHide_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cloud_None_C", "Active");

	Params::BP_Cloud_None_C_Active Parms{};

	Parms.bInstantHide_0 = bInstantHide_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Cloud_None.BP_Cloud_None_C.Hidden
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InstantHide                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Cloud_None_C::Hidden(bool InstantHide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Cloud_None_C", "Hidden");

	Params::BP_Cloud_None_C_Hidden Parms{};

	Parms.InstantHide = InstantHide;

	UObject::ProcessEvent(Func, &Parms);
}

}

