#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Feibi_Magic

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Feibi_Magic.BP_Feibi_Magic_C.ExecuteUbergraph_BP_Feibi_Magic
// 0x0004 (0x0004 - 0x0000)
struct BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic) == 0x000004, "Wrong alignment on BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic");
static_assert(sizeof(BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic) == 0x000004, "Wrong size on BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic");
static_assert(offsetof(BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic, EntryPoint) == 0x000000, "Member 'BP_Feibi_Magic_C_ExecuteUbergraph_BP_Feibi_Magic::EntryPoint' has a wrong offset!");

}

