#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GPUNPC_Group

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GPUNPC_Group.BP_GPUNPC_Group_C
// 0x0018 (0x02C8 - 0x02B0)
class ABP_GPUNPC_Group_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          HideLogicallyOnBeginPlay;                          // 0x02C0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, Interp, NoDestructor)

public:
	void ToggleHideInGame(bool isHide);
	void ReceiveBeginPlay();
	void DebugToggleVIsible();
	void ExecuteUbergraph_BP_GPUNPC_Group(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GPUNPC_Group_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GPUNPC_Group_C")
	}
	static class ABP_GPUNPC_Group_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GPUNPC_Group_C>();
	}
};
DUMPER7_ASSERTS_ABP_GPUNPC_Group_C;

}

