#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_KuroLightDecal

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_KuroLightDecal.BP_KuroLightDecal_C
// 0x0110 (0x03C8 - 0x02B8)
class ABP_KuroLightDecal_C : public ADecalActor
{
public:
	float                                         FadeScreenSize;                                    // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BC[0x4];                                      // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceConstant*              DecalMaterial;                                     // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, float>                      Scalars;                                           // 0x02C8(0x0050)(Edit, BlueprintVisible)
	TMap<class FName, class UTexture*>            Textures;                                          // 0x0318(0x0050)(Edit, BlueprintVisible)
	TMap<class FName, struct FLinearColor>        Vectors;                                           // 0x0368(0x0050)(Edit, BlueprintVisible)
	float                                         最小显示距离;                                      // 0x03B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         最大显示距离;                                      // 0x03BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         最小Fade距离;                                      // 0x03C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         最大Fade距离;                                      // 0x03C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void updateMaterialParameters();

	int32 GetPlacementSortOrder() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_KuroLightDecal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_KuroLightDecal_C")
	}
	static class ABP_KuroLightDecal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_KuroLightDecal_C>();
	}
};
DUMPER7_ASSERTS_ABP_KuroLightDecal_C;

}

