#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightModel

#include "Basic.hpp"

#include "BP_LightModel_classes.hpp"
#include "BP_LightModel_parameters.hpp"


namespace SDK
{

// Function BP_LightModel.BP_LightModel_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_LightModel_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightModel_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_LightModel.BP_LightModel_C.Custom Parameter
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         MaterialIns                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_LightModel_C::Custom_Parameter(class UMaterialInstanceDynamic* MaterialIns)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightModel_C", "Custom Parameter");

	Params::BP_LightModel_C_Custom_Parameter Parms{};

	Parms.MaterialIns = MaterialIns;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_LightModel.BP_LightModel_C.GetPlacementSortOrder
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 ABP_LightModel_C::GetPlacementSortOrder() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LightModel_C", "GetPlacementSortOrder");

	Params::BP_LightModel_C_GetPlacementSortOrder Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

