#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bp_NiagaraLeavesController

#include "Basic.hpp"

#include "Bp_NiagaraLeavesController_classes.hpp"
#include "Bp_NiagaraLeavesController_parameters.hpp"


namespace SDK
{

// Function Bp_NiagaraLeavesController.BP_NiagaraLeavesController_C.ExecuteUbergraph_BP_NiagaraLeavesController
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NiagaraLeavesController_C::ExecuteUbergraph_BP_NiagaraLeavesController(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NiagaraLeavesController_C", "ExecuteUbergraph_BP_NiagaraLeavesController");

	Params::BP_NiagaraLeavesController_C_ExecuteUbergraph_BP_NiagaraLeavesController Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Bp_NiagaraLeavesController.BP_NiagaraLeavesController_C.SetSpawnCountByScale
// (BlueprintCallable, BlueprintEvent)

void ABP_NiagaraLeavesController_C::SetSpawnCountByScale()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NiagaraLeavesController_C", "SetSpawnCountByScale");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Bp_NiagaraLeavesController.BP_NiagaraLeavesController_C.AddEffectActorByName
// (BlueprintCallable, BlueprintEvent)

void ABP_NiagaraLeavesController_C::AddEffectActorByName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NiagaraLeavesController_C", "AddEffectActorByName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Bp_NiagaraLeavesController.BP_NiagaraLeavesController_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NiagaraLeavesController_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NiagaraLeavesController_C", "ReceiveTick");

	Params::BP_NiagaraLeavesController_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Bp_NiagaraLeavesController.BP_NiagaraLeavesController_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NiagaraLeavesController_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NiagaraLeavesController_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Bp_NiagaraLeavesController.BP_NiagaraLeavesController_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_NiagaraLeavesController_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NiagaraLeavesController_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

