#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicInteractProxy

#include "Basic.hpp"

#include "BP_PhysicInteractProxy_classes.hpp"
#include "BP_PhysicInteractProxy_parameters.hpp"


namespace SDK
{

// Function BP_PhysicInteractProxy.BP_PhysicInteractProxy_C.SetRadiusAndHeight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   radius                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   height                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PhysicInteractProxy_C::SetRadiusAndHeight(float radius, float height)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PhysicInteractProxy_C", "SetRadiusAndHeight");

	Params::BP_PhysicInteractProxy_C_SetRadiusAndHeight Parms{};

	Parms.radius = radius;
	Parms.height = height;

	UObject::ProcessEvent(Func, &Parms);
}

}

