#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScreenSpaceTyndallScattering

#include "Basic.hpp"

#include "BP_ScreenSpaceTyndallScattering_classes.hpp"
#include "BP_ScreenSpaceTyndallScattering_parameters.hpp"


namespace SDK
{

// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.ExecuteUbergraph_BP_ScreenSpaceTyndallScattering
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ScreenSpaceTyndallScattering_C::ExecuteUbergraph_BP_ScreenSpaceTyndallScattering(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "ExecuteUbergraph_BP_ScreenSpaceTyndallScattering");

	Params::BP_ScreenSpaceTyndallScattering_C_ExecuteUbergraph_BP_ScreenSpaceTyndallScattering Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_ScreenSpaceTyndallScattering_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ScreenSpaceTyndallScattering_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "ReceiveEndPlay");

	Params::BP_ScreenSpaceTyndallScattering_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ScreenSpaceTyndallScattering_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "ReceiveTick");

	Params::BP_ScreenSpaceTyndallScattering_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ScreenSpaceTyndallScattering_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ScreenSpaceTyndallScattering_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScreenSpaceTyndallScattering.BP_ScreenSpaceTyndallScattering_C.tick
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ScreenSpaceTyndallScattering_C::tick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScreenSpaceTyndallScattering_C", "tick");

	UObject::ProcessEvent(Func, nullptr);
}

}

