#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shouanren

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TsBaseCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Shouanren.BP_Shouanren_C
// 0x0030 (0x0790 - 0x0760)
class ABP_Shouanren_C final : public ATsBaseCharacter_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Shouanren_C;                     // 0x0758(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UKuroAdjustableCapsuleComponent*        Bip001Spine2;                                      // 0x0760(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UKuroAdjustableCapsuleComponent*        Bip001LThighTwist;                                 // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UKuroAdjustableCapsuleComponent*        Bip001RThighTwist;                                 // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 OtherCase1;                                        // 0x0778(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 WeaponCase0;                                       // 0x0780(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Shouanren(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void FightCommand(bool isInAir);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Shouanren_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Shouanren_C")
	}
	static class ABP_Shouanren_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Shouanren_C>();
	}
};
DUMPER7_ASSERTS_ABP_Shouanren_C;

}

