#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SceneCapture_3To2

#include "Basic.hpp"

#include "BP_SceneCapture_3To2_classes.hpp"
#include "BP_SceneCapture_3To2_parameters.hpp"


namespace SDK
{

// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.ExecuteUbergraph_BP_SceneCapture_3To2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SceneCapture_3To2_C::ExecuteUbergraph_BP_SceneCapture_3To2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "ExecuteUbergraph_BP_SceneCapture_3To2");

	Params::BP_SceneCapture_3To2_C_ExecuteUbergraph_BP_SceneCapture_3To2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SceneCapture_3To2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_SceneCapture_3To2_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.EditorTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SceneCapture_3To2_C::EditorTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "EditorTick");

	Params::BP_SceneCapture_3To2_C_EditorTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.Resume
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::Resume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "Resume");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.Pause
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::Pause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "Pause");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.Stop
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::Stop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "Stop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.Start
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::Start()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "Start");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.TickOutside
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::TickOutside()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "TickOutside");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.CaptureScene_Running
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::CaptureScene_Running()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "CaptureScene_Running");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.SetEnablePPV
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Enable3To2Toggle                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SceneCapture_3To2_C::SetEnablePPV(float Enable3To2Toggle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "SetEnablePPV");

	Params::BP_SceneCapture_3To2_C_SetEnablePPV Parms{};

	Parms.Enable3To2Toggle = Enable3To2Toggle;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.ClearRT
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::ClearRT()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "ClearRT");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.AllowOcclusionQueries
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::AllowOcclusionQueries()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "AllowOcclusionQueries");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.EnableToonDepth
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::EnableToonDepth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "EnableToonDepth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.DisableToonDepth
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_SceneCapture_3To2_C::DisableToonDepth()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "DisableToonDepth");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.ShouldStopOnHide
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   ret                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_SceneCapture_3To2_C::ShouldStopOnHide(bool* ret)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "ShouldStopOnHide");

	Params::BP_SceneCapture_3To2_C_ShouldStopOnHide Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ret != nullptr)
		*ret = Parms.ret;
}


// Function BP_SceneCapture_3To2.BP_SceneCapture_3To2_C.GetAoiRange
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// int32*                                  ret                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SceneCapture_3To2_C::GetAoiRange(int32* ret) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SceneCapture_3To2_C", "GetAoiRange");

	Params::BP_SceneCapture_3To2_C_GetAoiRange Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ret != nullptr)
		*ret = Parms.ret;
}

}

