#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Vision_MB1Fuludelisi

#include "Basic.hpp"

#include "BP_BaseVision_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Vision_MB1Fuludelisi.BP_Vision_MB1Fuludelisi_C
// 0x0000 (0x0780 - 0x0780)
class ABP_Vision_MB1Fuludelisi_C final : public ABP_BaseVision_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Vision_MB1Fuludelisi_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Vision_MB1Fuludelisi_C")
	}
	static class ABP_Vision_MB1Fuludelisi_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Vision_MB1Fuludelisi_C>();
	}
};
DUMPER7_ASSERTS_ABP_Vision_MB1Fuludelisi_C;

}

