#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_CarPaintChange

#include "Basic.hpp"

#include "BPI_CarPaintChange_classes.hpp"
#include "BPI_CarPaintChange_parameters.hpp"


namespace SDK
{

// Function BPI_CarPaintChange.BPI_CarPaintChange_C.SetColorFunctionByBPI
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Bool                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void IBPI_CarPaintChange_C::SetColorFunctionByBPI(bool Bool)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BPI_CarPaintChange_C", "SetColorFunctionByBPI");

	Params::BPI_CarPaintChange_C_SetColorFunctionByBPI Parms{};

	Parms.Bool = Bool;

	AsUObject()->ProcessEvent(Func, &Parms);
}

}

