#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_NpcEcological

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_NpcEcological.BPI_NpcEcological_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_NpcEcological_C final
{
public:
	void HandlePlayerAttackEnd();
	void HandlePlayerAttack();
	void HandlePlayerImpactEnd();
	void HandlePlayerImpact();
	void HandlePlayerExit();
	void HandlePlayerEnter();
	void HandleQuestChanged();
	void HandleDayStateChanged();
	void HandleWeatherChanged();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_NpcEcological_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_NpcEcological_C")
	}
	static class IBPI_NpcEcological_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_NpcEcological_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_NpcEcological_C;

}

