#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ECommonQteViewType_SingleButtonLongPress

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ECommonQteViewType_SingleButtonLongPress.ECommonQteViewType_SingleButtonLongPress
// NumValues: 0x0006
enum class ECommonQteViewType_SingleButtonLongPress : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	ECommonQteViewType_MAX                   = 5,
};

}

