#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ME1QunJingMd00501_Attack09

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_Monster_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_ME1QunJingMd00501_Attack09.GA_ME1QunJingMd00501_Attack09_C
// 0x0008 (0x05E8 - 0x05E0)
class UGA_ME1QunJingMd00501_Attack09_C final : public UGA_Monster_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_ME1QunJingMd00501_Attack09_C;    // 0x05E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_ME1QunJingMd00501_Attack09(int32 EntryPoint);
	void K2_ActivateAbility();
	void Added_21071CB943CD992BF8EFD6A3A3F01621(const struct FGameplayTag& Tag);
	void OnCompleted_5D118C384AE61F1C80292E81FB074596();
	void OnBlendOut_5D118C384AE61F1C80292E81FB074596();
	void OnInterrupted_5D118C384AE61F1C80292E81FB074596();
	void OnCancelled_5D118C384AE61F1C80292E81FB074596();
	void OnTick_5D118C384AE61F1C80292E81FB074596();
	void EventReceived_18B59F5945020DB23C42FD88F38BD2CC(const struct FGameplayEventData& Payload);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_ME1QunJingMd00501_Attack09_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_ME1QunJingMd00501_Attack09_C")
	}
	static class UGA_ME1QunJingMd00501_Attack09_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_ME1QunJingMd00501_Attack09_C>();
	}
};
DUMPER7_ASSERTS_UGA_ME1QunJingMd00501_Attack09_C;

}

