#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Qiuyuan_Ex_Skill01

#include "Basic.hpp"

#include "GA_Qiuyuan_Ex_Skill01_classes.hpp"
#include "GA_Qiuyuan_Ex_Skill01_parameters.hpp"


namespace SDK
{

// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.ExecuteUbergraph_GA_Qiuyuan_Ex_Skill01
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Qiuyuan_Ex_Skill01_C::ExecuteUbergraph_GA_Qiuyuan_Ex_Skill01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "ExecuteUbergraph_GA_Qiuyuan_Ex_Skill01");

	Params::GA_Qiuyuan_Ex_Skill01_C_ExecuteUbergraph_GA_Qiuyuan_Ex_Skill01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_Qiuyuan_Ex_Skill01_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "K2_OnEndAbility");

	Params::GA_Qiuyuan_Ex_Skill01_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.Added_8FEE365C4E1AD1B6133BDF8CC55DF6CF
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Qiuyuan_Ex_Skill01_C::Added_8FEE365C4E1AD1B6133BDF8CC55DF6CF(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "Added_8FEE365C4E1AD1B6133BDF8CC55DF6CF");

	Params::GA_Qiuyuan_Ex_Skill01_C_Added_8FEE365C4E1AD1B6133BDF8CC55DF6CF Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnFinish_5AACE527495F3FF79191FDAE12BDD7A7
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnFinish_5AACE527495F3FF79191FDAE12BDD7A7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnFinish_5AACE527495F3FF79191FDAE12BDD7A7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.Added_4F01630F4C7C662AB5055FAE40A594AD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UGA_Qiuyuan_Ex_Skill01_C::Added_4F01630F4C7C662AB5055FAE40A594AD(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "Added_4F01630F4C7C662AB5055FAE40A594AD");

	Params::GA_Qiuyuan_Ex_Skill01_C_Added_4F01630F4C7C662AB5055FAE40A594AD Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCompleted_5D118C384AE61F1C80292E81E0146A6A
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCompleted_5D118C384AE61F1C80292E81E0146A6A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCompleted_5D118C384AE61F1C80292E81E0146A6A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnBlendOut_5D118C384AE61F1C80292E81E0146A6A
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnBlendOut_5D118C384AE61F1C80292E81E0146A6A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnBlendOut_5D118C384AE61F1C80292E81E0146A6A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnInterrupted_5D118C384AE61F1C80292E81E0146A6A
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnInterrupted_5D118C384AE61F1C80292E81E0146A6A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnInterrupted_5D118C384AE61F1C80292E81E0146A6A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCancelled_5D118C384AE61F1C80292E81E0146A6A
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCancelled_5D118C384AE61F1C80292E81E0146A6A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCancelled_5D118C384AE61F1C80292E81E0146A6A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnTick_5D118C384AE61F1C80292E81E0146A6A
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnTick_5D118C384AE61F1C80292E81E0146A6A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnTick_5D118C384AE61F1C80292E81E0146A6A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCompleted_5D118C384AE61F1C80292E8111990FD1
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCompleted_5D118C384AE61F1C80292E8111990FD1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCompleted_5D118C384AE61F1C80292E8111990FD1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnBlendOut_5D118C384AE61F1C80292E8111990FD1
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnBlendOut_5D118C384AE61F1C80292E8111990FD1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnBlendOut_5D118C384AE61F1C80292E8111990FD1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnInterrupted_5D118C384AE61F1C80292E8111990FD1
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnInterrupted_5D118C384AE61F1C80292E8111990FD1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnInterrupted_5D118C384AE61F1C80292E8111990FD1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCancelled_5D118C384AE61F1C80292E8111990FD1
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCancelled_5D118C384AE61F1C80292E8111990FD1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCancelled_5D118C384AE61F1C80292E8111990FD1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnTick_5D118C384AE61F1C80292E8111990FD1
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnTick_5D118C384AE61F1C80292E8111990FD1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnTick_5D118C384AE61F1C80292E8111990FD1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCompleted_5D118C384AE61F1C80292E815BD54AB4
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCompleted_5D118C384AE61F1C80292E815BD54AB4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCompleted_5D118C384AE61F1C80292E815BD54AB4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnBlendOut_5D118C384AE61F1C80292E815BD54AB4
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnBlendOut_5D118C384AE61F1C80292E815BD54AB4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnBlendOut_5D118C384AE61F1C80292E815BD54AB4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnInterrupted_5D118C384AE61F1C80292E815BD54AB4
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnInterrupted_5D118C384AE61F1C80292E815BD54AB4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnInterrupted_5D118C384AE61F1C80292E815BD54AB4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCancelled_5D118C384AE61F1C80292E815BD54AB4
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCancelled_5D118C384AE61F1C80292E815BD54AB4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCancelled_5D118C384AE61F1C80292E815BD54AB4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnTick_5D118C384AE61F1C80292E815BD54AB4
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnTick_5D118C384AE61F1C80292E815BD54AB4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnTick_5D118C384AE61F1C80292E815BD54AB4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCompleted_5D118C384AE61F1C80292E8196DAEEF6
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCompleted_5D118C384AE61F1C80292E8196DAEEF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCompleted_5D118C384AE61F1C80292E8196DAEEF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnBlendOut_5D118C384AE61F1C80292E8196DAEEF6
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnBlendOut_5D118C384AE61F1C80292E8196DAEEF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnBlendOut_5D118C384AE61F1C80292E8196DAEEF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnInterrupted_5D118C384AE61F1C80292E8196DAEEF6
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnInterrupted_5D118C384AE61F1C80292E8196DAEEF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnInterrupted_5D118C384AE61F1C80292E8196DAEEF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCancelled_5D118C384AE61F1C80292E8196DAEEF6
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCancelled_5D118C384AE61F1C80292E8196DAEEF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCancelled_5D118C384AE61F1C80292E8196DAEEF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnTick_5D118C384AE61F1C80292E8196DAEEF6
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnTick_5D118C384AE61F1C80292E8196DAEEF6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnTick_5D118C384AE61F1C80292E8196DAEEF6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCompleted_5D118C384AE61F1C80292E81CF6C2CCF
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCompleted_5D118C384AE61F1C80292E81CF6C2CCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCompleted_5D118C384AE61F1C80292E81CF6C2CCF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnBlendOut_5D118C384AE61F1C80292E81CF6C2CCF
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnBlendOut_5D118C384AE61F1C80292E81CF6C2CCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnBlendOut_5D118C384AE61F1C80292E81CF6C2CCF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnInterrupted_5D118C384AE61F1C80292E81CF6C2CCF
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnInterrupted_5D118C384AE61F1C80292E81CF6C2CCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnInterrupted_5D118C384AE61F1C80292E81CF6C2CCF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnCancelled_5D118C384AE61F1C80292E81CF6C2CCF
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnCancelled_5D118C384AE61F1C80292E81CF6C2CCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnCancelled_5D118C384AE61F1C80292E81CF6C2CCF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Qiuyuan_Ex_Skill01.GA_Qiuyuan_Ex_Skill01_C.OnTick_5D118C384AE61F1C80292E81CF6C2CCF
// (BlueprintCallable, BlueprintEvent)

void UGA_Qiuyuan_Ex_Skill01_C::OnTick_5D118C384AE61F1C80292E81CF6C2CCF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Qiuyuan_Ex_Skill01_C", "OnTick_5D118C384AE61F1C80292E81CF6C2CCF");

	UObject::ProcessEvent(Func, nullptr);
}

}

