#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Role_Manipulate

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BPE_ManipulateState_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "GA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Role_Manipulate.GA_Role_Manipulate_C
// 0x00A8 (0x0630 - 0x0588)
class UGA_Role_Manipulate_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Role_Manipulate_C;               // 0x0588(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCameraShakeBase*                       镜头震动;                                          // 0x0590(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 被控物Actor;                                       // 0x0598(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 物体actor;                                         // 0x05A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInterface*>             物体材质;                                          // 0x05A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	EBPE_ManipulateState                          控物状态;                                          // 0x05B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5B9[0x7];                                      // 0x05B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCameraShakeBase*                       当前镜头震动;                                      // 0x05C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerCameraManager*                   当前玩家镜头管理器;                                // 0x05C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<EBPE_ManipulateState, struct FGameplayTag> 子镜头;                                          // 0x05D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         _读条时间;                                         // 0x0620(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          正常下一步流程;                                    // 0x0624(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_625[0x3];                                      // 0x0625(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Entity_Id;                                         // 0x0628(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Role_Manipulate(int32 EntryPoint);
	void AfterRequest(bool bContent);
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);
	void OnCompleted_5D118C384AE61F1C80292E8150E58CB4();
	void OnBlendOut_5D118C384AE61F1C80292E8150E58CB4();
	void OnInterrupted_5D118C384AE61F1C80292E8150E58CB4();
	void OnCancelled_5D118C384AE61F1C80292E8150E58CB4();
	void OnTick_5D118C384AE61F1C80292E8150E58CB4();
	void OnFinish_C3FDF179485000A0038F85B4A18EE0C1();
	void EventReceived_A99B2F604F8C8EFCA354FB99DC615855(const struct FGameplayEventData& Payload);
	void EventReceived_216442174E3088EB354911B5CC57F2B1(const struct FGameplayEventData& Payload);
	void Added_21071CB943CD992BF8EFD6A385FA7D9C(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A302D055A4(const struct FGameplayTag& Tag);
	void OnCompleted_5D118C384AE61F1C80292E815237D5DE();
	void OnBlendOut_5D118C384AE61F1C80292E815237D5DE();
	void OnInterrupted_5D118C384AE61F1C80292E815237D5DE();
	void OnCancelled_5D118C384AE61F1C80292E815237D5DE();
	void OnTick_5D118C384AE61F1C80292E815237D5DE();
	void OnCompleted_5D118C384AE61F1C80292E81D680877C();
	void OnBlendOut_5D118C384AE61F1C80292E81D680877C();
	void OnInterrupted_5D118C384AE61F1C80292E81D680877C();
	void OnCancelled_5D118C384AE61F1C80292E81D680877C();
	void OnTick_5D118C384AE61F1C80292E81D680877C();
	void OnCompleted_5D118C384AE61F1C80292E815CB87408();
	void OnBlendOut_5D118C384AE61F1C80292E815CB87408();
	void OnInterrupted_5D118C384AE61F1C80292E815CB87408();
	void OnCancelled_5D118C384AE61F1C80292E815CB87408();
	void OnTick_5D118C384AE61F1C80292E815CB87408();
	void 选择释放控物动作方向(int32* 方向);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Role_Manipulate_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Role_Manipulate_C")
	}
	static class UGA_Role_Manipulate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Role_Manipulate_C>();
	}
};
DUMPER7_ASSERTS_UGA_Role_Manipulate_C;

}

