#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Role_Hook

#include "Basic.hpp"

#include "GA_Base_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Role_Hook.GA_Role_Hook_C
// 0x0048 (0x0618 - 0x05D0)
class UGA_Role_Hook_C final : public UGA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Role_Hook_C;                     // 0x05D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ATsBaseCharacter_C*                     角色;                                              // 0x05D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Forward;                                           // 0x05E0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                EndPos;                                            // 0x05EC(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InWater;                                           // 0x05F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5F9[0x7];                                      // 0x05F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVectorDouble                          LastLocation;                                      // 0x0600(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Role_Hook(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void K2_ActivateAbility();
	void OnCompleted_5D118C384AE61F1C80292E813209EC9F();
	void OnBlendOut_5D118C384AE61F1C80292E813209EC9F();
	void OnInterrupted_5D118C384AE61F1C80292E813209EC9F();
	void OnCancelled_5D118C384AE61F1C80292E813209EC9F();
	void OnTick_5D118C384AE61F1C80292E813209EC9F();
	void EventReceived_BE49D8B84159B3E2C93AFC8C33E21F9B(const struct FGameplayEventData& Payload);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Role_Hook_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Role_Hook_C")
	}
	static class UGA_Role_Hook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Role_Hook_C>();
	}
};
DUMPER7_ASSERTS_UGA_Role_Hook_C;

}

