#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_ShouAnRen_Burst_1st

#include "Basic.hpp"

#include "GA_ShouAnRen_Burst_1st_classes.hpp"
#include "GA_ShouAnRen_Burst_1st_parameters.hpp"


namespace SDK
{

// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.ExecuteUbergraph_GA_ShouAnRen_Burst_1st
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_ShouAnRen_Burst_1st_C::ExecuteUbergraph_GA_ShouAnRen_Burst_1st(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "ExecuteUbergraph_GA_ShouAnRen_Burst_1st");

	Params::GA_ShouAnRen_Burst_1st_C_ExecuteUbergraph_GA_ShouAnRen_Burst_1st Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_ShouAnRen_Burst_1st_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "K2_OnEndAbility");

	Params::GA_ShouAnRen_Burst_1st_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.OnCompleted_5D118C384AE61F1C80292E81C5D4E0D4
// (BlueprintCallable, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::OnCompleted_5D118C384AE61F1C80292E81C5D4E0D4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "OnCompleted_5D118C384AE61F1C80292E81C5D4E0D4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.OnBlendOut_5D118C384AE61F1C80292E81C5D4E0D4
// (BlueprintCallable, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::OnBlendOut_5D118C384AE61F1C80292E81C5D4E0D4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "OnBlendOut_5D118C384AE61F1C80292E81C5D4E0D4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.OnInterrupted_5D118C384AE61F1C80292E81C5D4E0D4
// (BlueprintCallable, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::OnInterrupted_5D118C384AE61F1C80292E81C5D4E0D4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "OnInterrupted_5D118C384AE61F1C80292E81C5D4E0D4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.OnCancelled_5D118C384AE61F1C80292E81C5D4E0D4
// (BlueprintCallable, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::OnCancelled_5D118C384AE61F1C80292E81C5D4E0D4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "OnCancelled_5D118C384AE61F1C80292E81C5D4E0D4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.OnTick_5D118C384AE61F1C80292E81C5D4E0D4
// (BlueprintCallable, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::OnTick_5D118C384AE61F1C80292E81C5D4E0D4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "OnTick_5D118C384AE61F1C80292E81C5D4E0D4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.EventReceived_18B59F5945020DB23C42FD88A5013A16
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_ShouAnRen_Burst_1st_C::EventReceived_18B59F5945020DB23C42FD88A5013A16(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "EventReceived_18B59F5945020DB23C42FD88A5013A16");

	Params::GA_ShouAnRen_Burst_1st_C_EventReceived_18B59F5945020DB23C42FD88A5013A16 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.领域生成位置
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTransformDouble                 ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor)

struct FTransformDouble UGA_ShouAnRen_Burst_1st_C::领域生成位置()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "领域生成位置");

	Params::GA_ShouAnRen_Burst_1st_C_领域生成位置 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GA_ShouAnRen_Burst_1st.GA_ShouAnRen_Burst_1st_C.领域初始化（设置可视并设置出生buff）
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_ShouAnRen_Burst_1st_C::领域初始化_设置可视并设置出生buff_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_ShouAnRen_Burst_1st_C", "领域初始化（设置可视并设置出生buff）");

	UObject::ProcessEvent(Func, nullptr);
}

}

