#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Vision_WaitAttack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "GA_Passive_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Vision_WaitAttack.GA_Vision_WaitAttack_C
// 0x0058 (0x0630 - 0x05D8)
class UGA_Vision_WaitAttack_C final : public UGa_Passive_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Vision_WaitAttack_C;             // 0x05D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ATsBaseCharacter_C*                     召唤角色;                                          // 0x05E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           普攻;                                              // 0x05E8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           蓄力;                                              // 0x05F4(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           技能;                                              // 0x0600(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           闪避反击;                                          // 0x060C(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           大招;                                              // 0x0618(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           瞄准射击;                                          // 0x0624(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Vision_WaitAttack(int32 EntryPoint);
	void K2_ActivateAbility();
	void Added_21071CB943CD992BF8EFD6A3CB2AA2EF(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A31BD89B52(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A3F86F70F6(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A3E7DDAD25(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A389E908C3(const struct FGameplayTag& Tag);
	void Added_21071CB943CD992BF8EFD6A3F34E6080(const struct FGameplayTag& Tag);
	void 允许攻击();
	void 赋予攻击目标();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Vision_WaitAttack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Vision_WaitAttack_C")
	}
	static class UGA_Vision_WaitAttack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Vision_WaitAttack_C>();
	}
};
DUMPER7_ASSERTS_UGA_Vision_WaitAttack_C;

}

