#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroAudioMaterial

#include "Basic.hpp"

#include "PhysicsCore_structs.hpp"
#include "KuroAudioMaterial_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class KuroAudioMaterial.KuroAudioMaterialSettings
// 0x0060 (0x0090 - 0x0030)
class UKuroAudioMaterialSettings final : public UObject
{
public:
	TArray<struct FKuroMatName2PhysMaterial>      MatName2PhysMaterial;                              // 0x0030(0x0010)(ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TMap<EPhysicalSurface, class FName>           FootstepAudioTextureMap;                           // 0x0040(0x0050)(Config, NativeAccessSpecifierPublic)

public:
	static class FName GetFootstepTextureName(EPhysicalSurface SurfaceType);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroAudioMaterialSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroAudioMaterialSettings")
	}
	static class UKuroAudioMaterialSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroAudioMaterialSettings>();
	}
};
DUMPER7_ASSERTS_UKuroAudioMaterialSettings;

// Class KuroAudioMaterial.KuroAudioMaterialSubsystem
// 0x0060 (0x0098 - 0x0038)
class UKuroAudioMaterialSubsystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_38[0x60];                                      // 0x0038(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool QueryInsideAnyFoliageInstance(const struct FVectorDouble& InQueryLocation, class FName* OutInstancedNames, class UPhysicalMaterial** OutPhysicalMaterial, class UStaticMeshComponent** OutStaicMeshComponent);
	bool QueryOverlapAnyFoliageInstance(const struct FBox& InQueryBounds, class FName* OutInstancedNames, class UPhysicalMaterial** OutPhysicalMaterial, class UStaticMeshComponent** OutStaicMeshComponent);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroAudioMaterialSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroAudioMaterialSubsystem")
	}
	static class UKuroAudioMaterialSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroAudioMaterialSubsystem>();
	}
};
DUMPER7_ASSERTS_UKuroAudioMaterialSubsystem;

}

