#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroGPUDrivenImposter

#include "Basic.hpp"

#include "KuroGPUDrivenImposter_classes.hpp"
#include "KuroGPUDrivenImposter_parameters.hpp"


namespace SDK
{

// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUpdater.ApplyGlobalSettings
// (Final, Native, Public, BlueprintCallable)

void AKuroGPUDrivenImposterUpdater::ApplyGlobalSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroGPUDrivenImposterUpdater", "ApplyGlobalSettings");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUpdater.FillAllInstGlobalColor
// (Final, Native, Public, BlueprintCallable)

void AKuroGPUDrivenImposterUpdater::FillAllInstGlobalColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroGPUDrivenImposterUpdater", "FillAllInstGlobalColor");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUpdater.UpdateImposters
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class UDirectionalLightComponent*       DirLight                                               (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKuroGPUDrivenImposterUpdater::UpdateImposters(class UDirectionalLightComponent* DirLight, float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KuroGPUDrivenImposterUpdater", "UpdateImposters");

	Params::KuroGPUDrivenImposterUpdater_UpdateImposters Parms{};

	Parms.DirLight = DirLight;
	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUtility.GenerateAll
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           EditorWorld                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bBake                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bClear                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroGPUDrivenImposterUtility::GenerateAll(class UWorld* EditorWorld, bool bBake, bool bClear)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroGPUDrivenImposterUtility", "GenerateAll");

	Params::KuroGPUDrivenImposterUtility_GenerateAll Parms{};

	Parms.EditorWorld = EditorWorld;
	Parms.bBake = bBake;
	Parms.bClear = bClear;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUtility.GetStableUploadBenchmarkStatus
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           World                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UKuroGPUDrivenImposterUtility::GetStableUploadBenchmarkStatus(class UWorld* World)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroGPUDrivenImposterUtility", "GetStableUploadBenchmarkStatus");

	Params::KuroGPUDrivenImposterUtility_GetStableUploadBenchmarkStatus Parms{};

	Parms.World = World;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUtility.RemoveAll
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           EditorWorld                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bClear                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroGPUDrivenImposterUtility::RemoveAll(class UWorld* EditorWorld, bool bClear)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroGPUDrivenImposterUtility", "RemoveAll");

	Params::KuroGPUDrivenImposterUtility_RemoveAll Parms{};

	Parms.EditorWorld = EditorWorld;
	Parms.bClear = bClear;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroGPUDrivenImposter.KuroGPUDrivenImposterUtility.StartStableUploadBenchmark
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UWorld*                           World                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   WarmupFrames                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   SampleFrames                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKuroGPUDrivenImposterUtility::StartStableUploadBenchmark(class UWorld* World, int32 WarmupFrames, int32 SampleFrames)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("KuroGPUDrivenImposterUtility", "StartStableUploadBenchmark");

	Params::KuroGPUDrivenImposterUtility_StartStableUploadBenchmark Parms{};

	Parms.World = World;
	Parms.WarmupFrames = WarmupFrames;
	Parms.SampleFrames = SampleFrames;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

