#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroInteractionEffect

#include "Basic.hpp"

#include "KuroInteractionEffect_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class KuroInteractionEffect.KuroEnviInteractionComponent
// 0x0170 (0x0230 - 0x00C0)
class UKuroEnviInteractionComponent final : public UActorComponent
{
public:
	uint8                                         Pad_C0[0x10];                                      // 0x00C0(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bCalEnviInteractionData;                           // 0x00D0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D1[0x3];                                       // 0x00D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                RayFromOffset;                                     // 0x00D4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                RayToOffset;                                       // 0x00E0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FrameCountToWaterTrace;                            // 0x00EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateWaterEID;                                   // 0x00F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateRainOcclusion;                              // 0x00F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseSPModelCharacterData;                          // 0x00F2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F3[0x1];                                       // 0x00F3(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ModelConfigId;                                     // 0x00F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ModelStateId;                                      // 0x00F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LinkNiagaraModeId;                                 // 0x00FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<int32, class UMaterialParameterCollection*> SPModelMPCMap;                                  // 0x0100(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	bool                                          bUseSPModelShiftColor;                             // 0x0150(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<int32, struct FSPModelSCPMap>            SPModelColorMap;                                   // 0x0158(0x0050)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A8[0x58];                                     // 0x01A8(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	class UTraceSphereElement*                    RainOcclusionTraceElement;                         // 0x0200(0x0008)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_208[0x28];                                     // 0x0208(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	struct FKuroEnviInteractionData GetEnviInteractionData();
	float GetRainWalkOcclusionParam();
	void RegisterComponentToSystem();
	void SetDecalCompShiftColor(class UDecalComponent* DecalComponent);
	void SetNiagaraCompShiftColor(class UNiagaraComponent* NiagaraComponent);
	void UpdateRainOcclusion(bool Result, class UTraceBaseElement* Element, double Frame, double Index_0);

	bool IsOccludedInRain() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroEnviInteractionComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroEnviInteractionComponent")
	}
	static class UKuroEnviInteractionComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroEnviInteractionComponent>();
	}
};
DUMPER7_ASSERTS_UKuroEnviInteractionComponent;

// Class KuroInteractionEffect.KuroIEMeshDebugActor
// 0x0028 (0x02D8 - 0x02B0)
class AKuroIEMeshDebugActor final : public AActor
{
public:
	class USceneComponent*                        SceneRoot;                                         // 0x02B0(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         LayoutPadding;                                     // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MaxRowWidth;                                       // 0x02BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class FName                                   GeneratedActorFolder;                              // 0x02C0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         CustomPrimitiveDataIndex;                          // 0x02CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FVector2D                              RandomCustomDataRange;                             // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void ClearGeneratedIEMeshDebugActors();
	void RebuildIEMeshDebugActors();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroIEMeshDebugActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroIEMeshDebugActor")
	}
	static class AKuroIEMeshDebugActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AKuroIEMeshDebugActor>();
	}
};
DUMPER7_ASSERTS_AKuroIEMeshDebugActor;

// Class KuroInteractionEffect.KuroInteractionEffectSystem
// 0x0418 (0x0450 - 0x0038)
class alignas(0x10) UKuroInteractionEffectSystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<TWeakObjectPtr<class UKuroEnviInteractionComponent>, struct FKuroEnviInteractionData> EnviInteractionCollections; // 0x0040(0x0050)(ContainsInstancedReference, NativeAccessSpecifierPublic)
	TMap<TWeakObjectPtr<class UNiagaraComponent>, TWeakObjectPtr<class UKuroEnviInteractionComponent>> SPModelEICompCollections; // 0x0090(0x0050)(ExportObject, ContainsInstancedReference, UObjectWrapper, NativeAccessSpecifierPublic)
	TMap<TWeakObjectPtr<class UNiagaraComponent>, TWeakObjectPtr<class UKuroEnviInteractionComponent>> NDIKuroRenderingCollections; // 0x00E0(0x0050)(ExportObject, ContainsInstancedReference, UObjectWrapper, NativeAccessSpecifierPublic)
	uint8                                         Pad_130[0x194];                                    // 0x0130(0x0194)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GrassCutReadBack;                                  // 0x02C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C8[0x8];                                      // 0x02C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataTable*                             IEMeshInteractionConfigTable;                      // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UMaterialParameterCollection*           WaterSimMPC;                                       // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2E0[0x170];                                    // 0x02E0(0x0170)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UKuroInteractionEffectSystem* GetKuroInteractionEffectSystem(class UWorld* World);

	void RegisterNDIKuroRenderingEIComp(class UNiagaraComponent* InNiagaraComp, class UKuroEnviInteractionComponent* SourceEIComp);
	void RegisterSPModelCharacterEIComp(class UNiagaraComponent* InNiagaraComp, class UKuroEnviInteractionComponent* SourceEIComp);
	int32 SearchInteractionFoliage(const class FString& FoliageTypeName);
	TArray<int32> SearchInteractionFoliageArray(const TArray<class FString>& FoliageTypeNames);
	struct FKuroInteractionEffectTraceStaticMesh SearchInteractionStaticMeshConfig(class UStaticMesh* StaticMesh);
	void SetGlobalUINiagaraPause(bool bPause);

	bool GetGlobalUINiagaraPause() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroInteractionEffectSystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroInteractionEffectSystem")
	}
	static class UKuroInteractionEffectSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroInteractionEffectSystem>();
	}
};
DUMPER7_ASSERTS_UKuroInteractionEffectSystem;

}

