#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroSceneInteraction_60

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KuroSceneInteraction_60.TPrefab_SM_Pro_SmallTow_2_0_C
// 0x0000 (0x02B8 - 0x02B8)
class KuroSceneInteraction_60::ATPrefab_SM_Pro_SmallTow_2_0_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass KuroSceneInteraction_60.TPrefab_SM_Pro_SmallTow_2_0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TPrefab_SM_Pro_SmallTow_2_0_C")
	}
	static class KuroSceneInteraction_60::ATPrefab_SM_Pro_SmallTow_2_0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<KuroSceneInteraction_60::ATPrefab_SM_Pro_SmallTow_2_0_C>();
	}
};
DUMPER7_ASSERTS_KuroSceneInteraction_60__ATPrefab_SM_Pro_SmallTow_2_0_C;

}

