#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroSceneUI

#include "Basic.hpp"

#include "KuroSceneUI_classes.hpp"
#include "KuroSceneUI_parameters.hpp"


namespace SDK
{

// Function KuroSceneUI.SceneUiAnchorActor.CloseUi
// (Final, Native, Public, BlueprintCallable)

void ASceneUiAnchorActor::CloseUi()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "CloseUi");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroSceneUI.SceneUiAnchorActor.DestroyUi
// (Final, Native, Public, BlueprintCallable)

void ASceneUiAnchorActor::DestroyUi()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "DestroyUi");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroSceneUI.SceneUiAnchorActor.Hide
// (Final, Native, Public, BlueprintCallable)

void ASceneUiAnchorActor::Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "Hide");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroSceneUI.SceneUiAnchorActor.Open
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ViewName                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Param                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASceneUiAnchorActor::Open(const class FString& ViewName, const class FString& Param)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "Open");

	Params::SceneUiAnchorActor_Open Parms{};

	Parms.ViewName = std::move(ViewName);
	Parms.Param = std::move(Param);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroSceneUI.SceneUiAnchorActor.OpenDefault
// (Final, Native, Public, BlueprintCallable)

void ASceneUiAnchorActor::OpenDefault()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "OpenDefault");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KuroSceneUI.SceneUiAnchorActor.OpenWithMap
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    ViewName                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TMap<class FString, class FString>&Params_0                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void ASceneUiAnchorActor::OpenWithMap(const class FString& ViewName, const TMap<class FString, class FString>& Params_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "OpenWithMap");

	Params::SceneUiAnchorActor_OpenWithMap Parms{};

	Parms.ViewName = std::move(ViewName);
	Parms.Params_0 = std::move(Params_0);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KuroSceneUI.SceneUiAnchorActor.Preload
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    ViewName                                               (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ASceneUiAnchorActor::Preload(const class FString& ViewName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SceneUiAnchorActor", "Preload");

	Params::SceneUiAnchorActor_Preload Parms{};

	Parms.ViewName = std::move(ViewName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

