#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KuroBulletCore

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "KuroBulletCore_structs.hpp"
#include "Engine_classes.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// Class KuroBulletCore.BulletActionBase
// 0x0008 (0x0038 - 0x0030)
class UBulletActionBase : public UObject
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletActionBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletActionBase")
	}
	static class UBulletActionBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletActionBase>();
	}
};
DUMPER7_ASSERTS_UBulletActionBase;

// Class KuroBulletCore.ActionInitBullet
// 0x0008 (0x0040 - 0x0038)
class UActionInitBullet : public UBulletActionBase
{
public:
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionInitBullet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionInitBullet")
	}
	static class UActionInitBullet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionInitBullet>();
	}
};
DUMPER7_ASSERTS_UActionInitBullet;

// Class KuroBulletCore.KuroBulletEmitterConfig
// 0x00F0 (0x0120 - 0x0030)
class UKuroBulletEmitterConfig : public UObject
{
public:
	struct FEmitterCommonSettings                 CommonSettings;                                    // 0x0030(0x00F0)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletEmitterConfig")
	}
	static class UKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_UKuroBulletEmitterConfig;

// Class KuroBulletCore.RectKuroBulletEmitterConfig
// 0x0068 (0x0188 - 0x0120)
class URectKuroBulletEmitterConfig final : public UKuroBulletEmitterConfig
{
public:
	struct FRectEmitterSettings                   RectSettings;                                      // 0x0120(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RectKuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RectKuroBulletEmitterConfig")
	}
	static class URectKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<URectKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_URectKuroBulletEmitterConfig;

// Class KuroBulletCore.BulletOnHitAction
// 0x0008 (0x0040 - 0x0038)
class UBulletOnHitAction : public UBulletActionBase
{
public:
	uint8                                         Pad_38[0x8];                                       // 0x0038(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletOnHitAction")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletOnHitAction")
	}
	static class UBulletOnHitAction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletOnHitAction>();
	}
};
DUMPER7_ASSERTS_UBulletOnHitAction;

// Class KuroBulletCore.ActionFlatGroundCollision
// 0x0000 (0x0038 - 0x0038)
class UActionFlatGroundCollision final : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionFlatGroundCollision")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionFlatGroundCollision")
	}
	static class UActionFlatGroundCollision* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionFlatGroundCollision>();
	}
};
DUMPER7_ASSERTS_UActionFlatGroundCollision;

// Class KuroBulletCore.ActionUpdateCollision
// 0x0000 (0x0038 - 0x0038)
class UActionUpdateCollision : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionUpdateCollision")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionUpdateCollision")
	}
	static class UActionUpdateCollision* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionUpdateCollision>();
	}
};
DUMPER7_ASSERTS_UActionUpdateCollision;

// Class KuroBulletCore.ActionUpdateMove
// 0x0000 (0x0038 - 0x0038)
class UActionUpdateMove : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionUpdateMove")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionUpdateMove")
	}
	static class UActionUpdateMove* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionUpdateMove>();
	}
};
DUMPER7_ASSERTS_UActionUpdateMove;

// Class KuroBulletCore.ActionChildBullet
// 0x0000 (0x0038 - 0x0038)
class UActionChildBullet final : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionChildBullet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionChildBullet")
	}
	static class UActionChildBullet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionChildBullet>();
	}
};
DUMPER7_ASSERTS_UActionChildBullet;

// Class KuroBulletCore.ActionDestroyBullet
// 0x0000 (0x0038 - 0x0038)
class UActionDestroyBullet final : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionDestroyBullet")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionDestroyBullet")
	}
	static class UActionDestroyBullet* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionDestroyBullet>();
	}
};
DUMPER7_ASSERTS_UActionDestroyBullet;

// Class KuroBulletCore.ActionInitBulletKFC
// 0x0000 (0x0040 - 0x0040)
class UActionInitBulletKFC final : public UActionInitBullet
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionInitBulletKFC")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionInitBulletKFC")
	}
	static class UActionInitBulletKFC* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionInitBulletKFC>();
	}
};
DUMPER7_ASSERTS_UActionInitBulletKFC;

// Class KuroBulletCore.ActionUpdateAtLast
// 0x0000 (0x0038 - 0x0038)
class UActionUpdateAtLast final : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionUpdateAtLast")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionUpdateAtLast")
	}
	static class UActionUpdateAtLast* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionUpdateAtLast>();
	}
};
DUMPER7_ASSERTS_UActionUpdateAtLast;

// Class KuroBulletCore.ActionUpdateLiveTime
// 0x0000 (0x0038 - 0x0038)
class UActionUpdateLiveTime final : public UBulletActionBase
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionUpdateLiveTime")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionUpdateLiveTime")
	}
	static class UActionUpdateLiveTime* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionUpdateLiveTime>();
	}
};
DUMPER7_ASSERTS_UActionUpdateLiveTime;

// Class KuroBulletCore.ActionUpdateTimeScale
// 0x0010 (0x0048 - 0x0038)
class UActionUpdateTimeScale final : public UBulletActionBase
{
public:
	uint8                                         Pad_38[0x10];                                      // 0x0038(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActionUpdateTimeScale")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActionUpdateTimeScale")
	}
	static class UActionUpdateTimeScale* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionUpdateTimeScale>();
	}
};
DUMPER7_ASSERTS_UActionUpdateTimeScale;

// Class KuroBulletCore.BulletContext
// 0x0000 (0x0000 - 0x0000)
class IBulletContext final
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletContext")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletContext")
	}
	static class IBulletContext* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBulletContext>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBulletContext;

// Class KuroBulletCore.BulletEntity
// 0x0560 (0x0590 - 0x0030)
class alignas(0x10) UBulletEntity final : public UObject
{
public:
	class AActor*                                 Actor;                                             // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x2C];                                      // 0x0038(0x002C)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         EntityId;                                          // 0x0064(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         ConfigId;                                          // 0x0068(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_70[0x8];                                       // 0x0070(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IBulletContext>        BulletContext;                                     // 0x0078(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)
	uint8                                         Pad_88[0xC0];                                      // 0x0088(0x00C0)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    CollisionComponent;                                // 0x0148(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UBulletKFCComponent*                    KFCComponent;                                      // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_158[0xD0];                                     // 0x0158(0x00D0)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bNeedDetach;                                       // 0x0228(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_229[0x67];                                     // 0x0229(0x0067)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class UObject*, class UBulletHitActorData*> MapHitActorData;                                // 0x0290(0x0050)(NativeAccessSpecifierPublic)
	TArray<class UBulletHitActorData*>            ArrayHitActorData;                                 // 0x02E0(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TMap<class UObject*, class UBulletHitActorData*> LastMapHitActorData;                            // 0x02F0(0x0050)(NativeAccessSpecifierPublic)
	TArray<class UBulletHitActorData*>            LastArrayHitActorData;                             // 0x0340(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_350[0x8];                                      // 0x0350(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UTraceSphereElement*                    ObstacleTraceSphere;                               // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTraceBoxElement*                       ObstacleTraceBox;                                  // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTraceLineElement*                      ObstacleTraceLine;                                 // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_370[0x1B0];                                    // 0x0370(0x01B0)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UBulletActionBase*>              TickActions;                                       // 0x0520(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TArray<class UBulletOnHitAction*>             OnHitActions;                                      // 0x0530(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_540[0x50];                                     // 0x0540(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnObstacleTrace(bool Result, class UTraceBaseElement* Element, double Frame, double Index_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletEntity")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletEntity")
	}
	static class UBulletEntity* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletEntity>();
	}
};
DUMPER7_ASSERTS_UBulletEntity;

// Class KuroBulletCore.BulletHitActorData
// 0x0058 (0x0088 - 0x0030)
class UBulletHitActorData final : public UObject
{
public:
	uint8                                         Pad_30[0x58];                                      // 0x0030(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletHitActorData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletHitActorData")
	}
	static class UBulletHitActorData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletHitActorData>();
	}
};
DUMPER7_ASSERTS_UBulletHitActorData;

// Class KuroBulletCore.BulletKFCComponent
// 0x0090 (0x00C0 - 0x0030)
class alignas(0x10) UBulletKFCComponent final : public UObject
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UBulletEntity*                          BulletEntity;                                      // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_40[0x80];                                      // 0x0040(0x0080)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletKFCComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletKFCComponent")
	}
	static class UBulletKFCComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletKFCComponent>();
	}
};
DUMPER7_ASSERTS_UBulletKFCComponent;

// Class KuroBulletCore.BulletWorld
// 0x04B8 (0x04E8 - 0x0030)
class UBulletWorld final : public UObject
{
public:
	uint8                                         Pad_30[0x20];                                      // 0x0030(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	class UTraceLineElement*                      StickGroundLineTrace;                              // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFlatGround;                                       // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        GroundZ;                                           // 0x0060(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ForceUpdateOverlap;                                // 0x0068(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(int32 EntityId, int64 BuffId, bool bAdd)> OnBulletModifyBuff;      // 0x0070(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(const class FString& ShakePath)> OnBulletCameraShake;              // 0x0080(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	bool                                          EnableRecycledId;                                  // 0x0090(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_91[0x3];                                       // 0x0091(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxBulletCount;                                    // 0x0094(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CreateBulletBudgetPerSecondMicroseconds;           // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CreateBulletBudgetBurstSeconds;                    // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          EnableBulletNoActor;                               // 0x00A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UDataTable*>                     CommonBulletDataTableList;                         // 0x00B0(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TMap<int32, class UBulletEntity*>             BulletEntityMap;                                   // 0x00C0(0x0050)(NativeAccessSpecifierPrivate)
	TMap<int32, class UKuroBulletPattern*>        BulletPatternMap;                                  // 0x0110(0x0050)(NativeAccessSpecifierPrivate)
	uint8                                         Pad_160[0x10];                                     // 0x0160(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	class UKuroBulletObstacle*                    GroundObstacleObject;                              // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class UObject*>                        ObjectHold;                                        // 0x0178(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_188[0xC8];                                     // 0x0188(0x00C8)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FDeferredBulletSpawn>           DeferredSpawnQueue;                                // 0x0250(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_260[0x280];                                    // 0x0260(0x0280)(Fixing Size After Last Property [ Dumper-7 ])
	class UKuroFastCollisionAlgorithm*            KFCAlgorithm;                                      // 0x04E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void AddCommonBulletDataTable(class UDataTable* DataTable);
	void ClearCameraShakeConfig();
	void ClearCommonBulletDataTable();
	int32 CreateBullet(TScriptInterface<class IBulletContext> BulletContext, int64 BulletConfigId, const struct FBulletSpawnParams& SpawnParams);
	void DestroyAllBulletsByOwner(const class AActor* Owner);
	void DestroyAllPatterns();
	void DestroyBullet(class UBulletEntity* BulletEntity, bool ClearContext);
	void DestroyBulletById(int32 BulletEntityId, bool ClearContext);
	void DestroyPattern(int32 PatternId);
	void DestroyPatternsByOwner(const class AActor* Owner);
	void DisableFlatGround();
	void EnableFlatGround(double Height);
	void EnableFlatGroundByAbovePoint(const struct FVectorDouble& AbovePoint);
	bool FindBulletConfig(int64 BulletConfigId, class UDataTable* OwnerBulletDataTable, struct FKuroBulletData* OutRow);
	bool InitBulletConfig(class UBulletEntity* BulletEntity, int64 BulletConfigId, class UDataTable* OwnerBulletDataTable);
	class UObject* PoolGet(class UClass* Cls);
	void RegisterBulletActionClass(EKuroBulletCoreActionType ActionType, TSubclassOf<class UBulletActionBase> ActionClass);
	void RegisterBulletActionClassByTag(const struct FGameplayTag& ActionTag, TSubclassOf<class UBulletActionBase> ActionClass);
	void RegisterBulletLogicActionClass(TSubclassOf<class UKuroBulletBpDataAsset> LogicAssetClass, TSubclassOf<class UBulletActionBase> ActionClass);
	void RegisterCameraShakeConfig(int32 ShakeKey, const class FString& ShakePath);
	void SetBulletGroupMaxCountSingle(int32 GroupId, int32 MaxCount);
	void SetCameraShakeCooldown(double Cooldown);
	void SetKFCAlgorithm(class UKuroFastCollisionAlgorithm* Algorithm);
	void SetShowBulletCollision(bool Value);
	void SetShowEmitterDebugDraw(bool Value);
	int32 SpawnPattern(TScriptInterface<class IBulletContext> PatternContext, const class UKuroBulletPatternDataAsset* PatternDA);

	class UBulletEntity* GetBulletEntity(int32 EntityId) const;
	int32 GetBulletGroupActiveCount(int32 GroupId) const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BulletWorld")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BulletWorld")
	}
	static class UBulletWorld* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBulletWorld>();
	}
};
DUMPER7_ASSERTS_UBulletWorld;

// Class KuroBulletCore.KuroBulletCoreSubsystem
// 0x0000 (0x0038 - 0x0038)
class UKuroBulletCoreSubsystem final : public UGameInstanceSubsystem
{
public:
	class UBulletWorld* CreateWorld();
	void DestroyWorld();
	class UBulletWorld* GetBulletWorld();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletCoreSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletCoreSubsystem")
	}
	static class UKuroBulletCoreSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletCoreSubsystem>();
	}
};
DUMPER7_ASSERTS_UKuroBulletCoreSubsystem;

// Class KuroBulletCore.KuroBulletBpDataAsset
// 0x0000 (0x0038 - 0x0038)
class UKuroBulletBpDataAsset : public UPrimaryDataAsset
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletBpDataAsset")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletBpDataAsset")
	}
	static class UKuroBulletBpDataAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletBpDataAsset>();
	}
};
DUMPER7_ASSERTS_UKuroBulletBpDataAsset;

// Class KuroBulletCore.KuroBulletBpDataAssetGroup
// 0x0010 (0x0048 - 0x0038)
class UKuroBulletBpDataAssetGroup final : public UDataAsset
{
public:
	TArray<class UKuroBulletBpDataAsset*>         Data;                                              // 0x0038(0x0010)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletBpDataAssetGroup")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletBpDataAssetGroup")
	}
	static class UKuroBulletBpDataAssetGroup* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletBpDataAssetGroup>();
	}
};
DUMPER7_ASSERTS_UKuroBulletBpDataAssetGroup;

// Class KuroBulletCore.KuroBulletLogicDataBase
// 0x0008 (0x0040 - 0x0038)
class UKuroBulletLogicDataBase : public UKuroBulletBpDataAsset
{
public:
	EKuroBulletLogicStage                         ExecuteStage;                                      // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletLogicDataBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletLogicDataBase")
	}
	static class UKuroBulletLogicDataBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletLogicDataBase>();
	}
};
DUMPER7_ASSERTS_UKuroBulletLogicDataBase;

// Class KuroBulletCore.KuroBulletEmitter
// 0x00B8 (0x00E8 - 0x0030)
class UKuroBulletEmitter : public UObject
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UKuroBulletPattern*                     OwnerPattern;                                      // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UKuroBulletEmitterConfig*               EmitterConfig;                                     // 0x0040(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_48[0x18];                                      // 0x0048(0x0018)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 SpawnedBulletIds;                                  // 0x0060(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_70[0x78];                                      // 0x0070(0x0078)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletEmitter")
	}
	static class UKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_UKuroBulletEmitter;

// Class KuroBulletCore.CircleKuroBulletEmitter
// 0x0008 (0x00F0 - 0x00E8)
class UCircleKuroBulletEmitter final : public UKuroBulletEmitter
{
public:
	class UCircleKuroBulletEmitterConfig*         CircleConfig;                                      // 0x00E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CircleKuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CircleKuroBulletEmitter")
	}
	static class UCircleKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCircleKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_UCircleKuroBulletEmitter;

// Class KuroBulletCore.SphereKuroBulletEmitter
// 0x0008 (0x00F0 - 0x00E8)
class USphereKuroBulletEmitter final : public UKuroBulletEmitter
{
public:
	class USphereKuroBulletEmitterConfig*         SphereConfig;                                      // 0x00E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SphereKuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SphereKuroBulletEmitter")
	}
	static class USphereKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<USphereKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_USphereKuroBulletEmitter;

// Class KuroBulletCore.PolygonKuroBulletEmitter
// 0x0008 (0x00F0 - 0x00E8)
class UPolygonKuroBulletEmitter final : public UKuroBulletEmitter
{
public:
	class UPolygonKuroBulletEmitterConfig*        PolygonConfig;                                     // 0x00E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PolygonKuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PolygonKuroBulletEmitter")
	}
	static class UPolygonKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPolygonKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_UPolygonKuroBulletEmitter;

// Class KuroBulletCore.StarKuroBulletEmitter
// 0x0008 (0x00F0 - 0x00E8)
class UStarKuroBulletEmitter final : public UKuroBulletEmitter
{
public:
	class UStarKuroBulletEmitterConfig*           StarConfig;                                        // 0x00E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StarKuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StarKuroBulletEmitter")
	}
	static class UStarKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStarKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_UStarKuroBulletEmitter;

// Class KuroBulletCore.RectKuroBulletEmitter
// 0x0008 (0x00F0 - 0x00E8)
class URectKuroBulletEmitter final : public UKuroBulletEmitter
{
public:
	class URectKuroBulletEmitterConfig*           RectConfig;                                        // 0x00E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RectKuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RectKuroBulletEmitter")
	}
	static class URectKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<URectKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_URectKuroBulletEmitter;

// Class KuroBulletCore.CircleRandomKuroBulletEmitter
// 0x0008 (0x00F0 - 0x00E8)
class UCircleRandomKuroBulletEmitter final : public UKuroBulletEmitter
{
public:
	class UCircleRandomKuroBulletEmitterConfig*   CircleConfig;                                      // 0x00E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CircleRandomKuroBulletEmitter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CircleRandomKuroBulletEmitter")
	}
	static class UCircleRandomKuroBulletEmitter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCircleRandomKuroBulletEmitter>();
	}
};
DUMPER7_ASSERTS_UCircleRandomKuroBulletEmitter;

// Class KuroBulletCore.KuroBulletFunctionLibrary
// 0x0000 (0x0030 - 0x0030)
class UKuroBulletFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void DestroyBulletById(int32 BulletEntityId, bool ClearOwner);
	static void DestroyPattern(int32 PatternId);
	static void DestroyPatternsByOwner(const class AActor* Owner);
	static void SetShowBulletCollision(bool Value);
	static void SetShowEmitterDebugDraw(bool Value);
	static int32 SpawnPattern(TScriptInterface<class IBulletContext> PatternContext, const class UKuroBulletPatternDataAsset* PatternDA);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletFunctionLibrary")
	}
	static class UKuroBulletFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UKuroBulletFunctionLibrary;

// Class KuroBulletCore.KuroBulletLogicDataWhirlpool
// 0x0028 (0x0068 - 0x0040)
class UKuroBulletLogicDataWhirlpool final : public UKuroBulletLogicDataBase
{
public:
	float                                         MoveTime;                                          // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         WeightLimit;                                       // 0x0044(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EKuroBulletWhirlpoolVelocityCurveType         VelocityCurve;                                     // 0x0048(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           TagNeed;                                           // 0x004C(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   AttackerSocketName;                                // 0x0058(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          CancelByHit;                                       // 0x0064(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletLogicDataWhirlpool")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletLogicDataWhirlpool")
	}
	static class UKuroBulletLogicDataWhirlpool* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletLogicDataWhirlpool>();
	}
};
DUMPER7_ASSERTS_UKuroBulletLogicDataWhirlpool;

// Class KuroBulletCore.KuroBulletLogicDataWorldBulletInteract
// 0x0018 (0x0058 - 0x0040)
class UKuroBulletLogicDataWorldBulletInteract final : public UKuroBulletLogicDataBase
{
public:
	TArray<EWorldBulletType>                      InteractionWorldBulletTypes;                       // 0x0040(0x0010)(Edit, BlueprintVisible, ZeroConstructor, NativeAccessSpecifierPublic)
	EKuroBulletInteract                           WorldBulletInteractType;                           // 0x0050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletLogicDataWorldBulletInteract")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletLogicDataWorldBulletInteract")
	}
	static class UKuroBulletLogicDataWorldBulletInteract* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletLogicDataWorldBulletInteract>();
	}
};
DUMPER7_ASSERTS_UKuroBulletLogicDataWorldBulletInteract;

// Class KuroBulletCore.KuroBulletObstacle
// 0x0000 (0x0030 - 0x0030)
class UKuroBulletObstacle final : public UObject
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletObstacle")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletObstacle")
	}
	static class UKuroBulletObstacle* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletObstacle>();
	}
};
DUMPER7_ASSERTS_UKuroBulletObstacle;

// Class KuroBulletCore.KuroBulletPattern
// 0x00F0 (0x0120 - 0x0030)
class UKuroBulletPattern final : public UObject
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UKuroBulletPatternDataAsset*            PatternDataAsset;                                  // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TScriptInterface<class IBulletContext>        PatternContext;                                    // 0x0040(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	uint8                                         Pad_50[0x8];                                       // 0x0050(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UKuroBulletEmitter*>             Emitters;                                          // 0x0058(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_68[0xB8];                                      // 0x0068(0x00B8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletPattern")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletPattern")
	}
	static class UKuroBulletPattern* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletPattern>();
	}
};
DUMPER7_ASSERTS_UKuroBulletPattern;

// Class KuroBulletCore.CircleKuroBulletEmitterConfig
// 0x0068 (0x0188 - 0x0120)
class UCircleKuroBulletEmitterConfig final : public UKuroBulletEmitterConfig
{
public:
	struct FCircleEmitterSettings                 CircleSettings;                                    // 0x0120(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CircleKuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CircleKuroBulletEmitterConfig")
	}
	static class UCircleKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCircleKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_UCircleKuroBulletEmitterConfig;

// Class KuroBulletCore.SphereKuroBulletEmitterConfig
// 0x0018 (0x0138 - 0x0120)
class USphereKuroBulletEmitterConfig final : public UKuroBulletEmitterConfig
{
public:
	struct FSphereEmitterSettings                 SphereSettings;                                    // 0x0120(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, NoDestructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SphereKuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SphereKuroBulletEmitterConfig")
	}
	static class USphereKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<USphereKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_USphereKuroBulletEmitterConfig;

// Class KuroBulletCore.PolygonKuroBulletEmitterConfig
// 0x0068 (0x0188 - 0x0120)
class UPolygonKuroBulletEmitterConfig final : public UKuroBulletEmitterConfig
{
public:
	struct FPolygonEmitterSettings                PolygonSettings;                                   // 0x0120(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PolygonKuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PolygonKuroBulletEmitterConfig")
	}
	static class UPolygonKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPolygonKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_UPolygonKuroBulletEmitterConfig;

// Class KuroBulletCore.StarKuroBulletEmitterConfig
// 0x0068 (0x0188 - 0x0120)
class UStarKuroBulletEmitterConfig final : public UKuroBulletEmitterConfig
{
public:
	struct FStarEmitterSettings                   StarSettings;                                      // 0x0120(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StarKuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StarKuroBulletEmitterConfig")
	}
	static class UStarKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStarKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_UStarKuroBulletEmitterConfig;

// Class KuroBulletCore.CircleRandomKuroBulletEmitterConfig
// 0x0070 (0x0190 - 0x0120)
class UCircleRandomKuroBulletEmitterConfig final : public UKuroBulletEmitterConfig
{
public:
	float                                         BaseRadius;                                        // 0x0120(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_124[0x4];                                      // 0x0124(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FCircleRandomEmitterSettings>   CircleRandomSettings;                              // 0x0128(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NativeAccessSpecifierPublic)
	struct FEmitterStackSettings                  StackSettings;                                     // 0x0138(0x0058)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CircleRandomKuroBulletEmitterConfig")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CircleRandomKuroBulletEmitterConfig")
	}
	static class UCircleRandomKuroBulletEmitterConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCircleRandomKuroBulletEmitterConfig>();
	}
};
DUMPER7_ASSERTS_UCircleRandomKuroBulletEmitterConfig;

// Class KuroBulletCore.KuroBulletPatternDataAsset
// 0x0018 (0x0050 - 0x0038)
class UKuroBulletPatternDataAsset final : public UPrimaryDataAsset
{
public:
	EBulletPatternDestroyType                     DestroyType;                                       // 0x0038(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         PatternDuration;                                   // 0x003C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FEmitterNode>                   EmitterNodes;                                      // 0x0040(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("KuroBulletPatternDataAsset")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"KuroBulletPatternDataAsset")
	}
	static class UKuroBulletPatternDataAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKuroBulletPatternDataAsset>();
	}
};
DUMPER7_ASSERTS_UKuroBulletPatternDataAsset;

}

