#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RockNShake_3

#include "Basic.hpp"

#include "KuroAnim_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RockNShake_3.RockNShake_3_C
// 0x0000 (0x01D0 - 0x01D0)
class URockNShake_3_C final : public UKuroCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RockNShake_3_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RockNShake_3_C")
	}
	static class URockNShake_3_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URockNShake_3_C>();
	}
};
DUMPER7_ASSERTS_URockNShake_3_C;

}

