#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SFreeFollowingConfig

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct SFreeFollowingConfig.SFreeFollowingConfig
// 0x0048 (0x0048 - 0x0000)
struct FSFreeFollowingConfig final
{
public:
	bool                                          Enable_1_188850A14E380C4CD5250EAA6D5277A5;         // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          FollowOnRight_3_B94EF4754BA5A2709A86309C5AE7C8DF;  // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          AutoChangeSide_5_2C7BF1A64C014F154FFC3B8D23582EB8; // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         StartFollowingRadius_21_0130C07A4A7A23469B79DAAD18D653D3; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WalkStartFollowingRadius_27_7652D0C247F902EAA3A7BEBB40FAB4B7; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FollowRadius_10_67C1C43549E36E4C527642A335D55B5D;  // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WalkFollowRadius_25_8B80324F4364B8F0EDCF8BA0C37970EA; // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxForwardOffset_11_EDE686114EAC71520F5D76861DE25DE5; // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FullForwardOffsetSpeed_13_16545433457D79CC8BE136BE33BC4595; // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SideAngleTolerance_15_CE458A85428E3D010E1962B1048F778C; // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OffsetAngle_23_F1936E0C40C9DBE7A2F24987E55F90A7;   // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MovementIntentSmoothingTime_33_3366FF5F4909D07B878DFE9D1F4B7373; // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         StopConfirmTime_39_D45DB2F6483F2814D75C8A8CA92A00A0; // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WalkBehindTargetPauseTime_41_4D71B47C45F33B60FFE899A7122459D8; // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RunReferenceDirectionSmoothingTime_43_404B654246BA66A9FC7B45863114FF72; // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SprintReferenceDirectionSmoothingTime_45_4A284434428A9D2053107F92688F4D6B; // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableLocalMovementHold_30_086189CE484ADA5236F2A69F5D3BFF2F; // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LocalMovementEnterRate_35_DBA8615F48853384FC3CD39F06EE403D; // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LocalMovementEnterConfirmTime_37_021D62CE4F5D93A1A3B8889563C1F291; // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DebugDraw_18_1951006F403EB7AF2E6CB6AB56540535;     // 0x0044(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_FSFreeFollowingConfig;

}

