#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SQta

#include "Basic.hpp"

#include "SQtaCondition_structs.hpp"
#include "SQtaBase_structs.hpp"
#include "SQtaPrompt_structs.hpp"
#include "SQtaResultAction_structs.hpp"


namespace SDK
{

// UserDefinedStruct SQta.SQta
// 0x0130 (0x0130 - 0x0000)
struct FSQta final
{
public:
	class FString                                 Desc_2_5588615B4CECAB4B6807E586B5F6BD07;           // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Priority_66_C2B1A38346D3BF560E149E90B0B9D232;      // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AutonomousOnly_75_F80376D6453D603A0495858F43A5FABB; // 0x0014(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSQtaCondition                         ActiveCondition_69_1FB4BB6B4452052991C0BF8D5BD08BF9; // 0x0018(0x0020)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSQtaCondition                         DeactiveCondition_70_2197AFD940C57E2EB1E53A8439FC8188; // 0x0038(0x0020)(Edit, BlueprintVisible, HasGetValueTypeHash)
	struct FSQtaBase                              BaseConfig_33_C3972A8C48D3A646DEA5B6AE502159D4;    // 0x0058(0x00B0)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct FSQtaPrompt>                    Prompt_72_296C3E1E4D27A1FA12B43D992BA2B52B;        // 0x0108(0x0010)(Edit, BlueprintVisible)
	TArray<struct FSQtaResultAction>              ResultAction_71_FF64DC7F47513AA9A40D749AF8518CC4;  // 0x0118(0x0010)(Edit, BlueprintVisible)
	bool                                          EndActiveSkill_77_6DB8C4BA4128E4951ABA3DB4497E126E; // 0x0128(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          EndSkillWhenDeactive_83_716D93324083F5F0DA2D27AE2DB3D038; // 0x0129(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          HandleFailWhenInvalidStop_81_BD81DEA04E02BF7D9F4468B974BCFD23; // 0x012A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          StopWhenFightInputBlocked_79_F4935E50492ECF683A65009D55421CEC; // 0x012B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_FSQta;

}

