#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SScenePropertyEffect

#include "Basic.hpp"

#include "SSceneInteractionMaterialController_structs.hpp"


namespace SDK
{

// UserDefinedStruct SScenePropertyEffect.SScenePropertyEffect
// 0x0038 (0x0038 - 0x0000)
struct FSScenePropertyEffect final
{
public:
	struct FSSceneInteractionMaterialController   Material_2_42A504A247C73A6A52C2AFB9987F7938;       // 0x0000(0x0030)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class ABP_EffectActor_C*                      Effect_6_381D9DA246E968C079A4BC8DA61C8B3C;         // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FSScenePropertyEffect;

}

