#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StandinActor

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "SimplygonUObjects_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "StandinActor_structs.hpp"


namespace SDK
{

// Class StandinActor.StandInMeshActor
// 0x0008 (0x02B8 - 0x02B0)
class AStandInMeshActor final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMeshComponent;                               // 0x02B0(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StandInMeshActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StandInMeshActor")
	}
	static class AStandInMeshActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AStandInMeshActor>();
	}
};
DUMPER7_ASSERTS_AStandInMeshActor;

// Class StandinActor.SimplygonStandinPipeline
// 0x0068 (0x0098 - 0x0030)
class USimplygonStandinPipeline : public UObject
{
public:
	struct FChartAggregatorSettings               ChartAggregatorSettings;                           // 0x0030(0x0038)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FMaterialOutputSettings                MaterialOutputSettings;                            // 0x0068(0x0030)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SimplygonStandinPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SimplygonStandinPipeline")
	}
	static class USimplygonStandinPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<USimplygonStandinPipeline>();
	}
};
DUMPER7_ASSERTS_USimplygonStandinPipeline;

// Class StandinActor.StandinNearPipeline
// 0x0210 (0x02A8 - 0x0098)
class UStandinNearPipeline final : public USimplygonStandinPipeline
{
public:
	struct FAggregationPipelineSettings           Settings;                                          // 0x0098(0x01F0)(Edit, BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FNearStandinLightmapSettings           LightmapSettings;                                  // 0x0288(0x001C)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A4[0x4];                                      // 0x02A4(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StandinNearPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StandinNearPipeline")
	}
	static class UStandinNearPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandinNearPipeline>();
	}
};
DUMPER7_ASSERTS_UStandinNearPipeline;

// Class StandinActor.StandinFarPipeline
// 0x0238 (0x02D0 - 0x0098)
class UStandinFarPipeline final : public USimplygonStandinPipeline
{
public:
	struct FRemeshingPipelineSettings             Settings;                                          // 0x0098(0x0230)(Edit, BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FStandinLightmapSettings               LightmapSettings;                                  // 0x02C8(0x0008)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StandinFarPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StandinFarPipeline")
	}
	static class UStandinFarPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandinFarPipeline>();
	}
};
DUMPER7_ASSERTS_UStandinFarPipeline;

// Class StandinActor.BillboardCloudPipeline
// 0x0138 (0x01D0 - 0x0098)
class UBillboardCloudPipeline final : public USimplygonStandinPipeline
{
public:
	struct FBillboardCloudPipelineSettings        Settings;                                          // 0x0098(0x0130)(Edit, BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FStandinLightmapSettings               LightmapSettings;                                  // 0x01C8(0x0008)(Edit, BlueprintVisible, NoDestructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("BillboardCloudPipeline")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BillboardCloudPipeline")
	}
	static class UBillboardCloudPipeline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBillboardCloudPipeline>();
	}
};
DUMPER7_ASSERTS_UBillboardCloudPipeline;

// Class StandinActor.StandinProxyContainer
// 0x0010 (0x0040 - 0x0030)
class UStandinProxyContainer final : public UObject
{
public:
	TArray<struct FStandinProxyEntry>             Standins;                                          // 0x0030(0x0010)(Edit, ZeroConstructor, EditConst, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("StandinProxyContainer")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StandinProxyContainer")
	}
	static class UStandinProxyContainer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStandinProxyContainer>();
	}
};
DUMPER7_ASSERTS_UStandinProxyContainer;

}

