#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TPrefab_SM_Pro_SmallTow_2_0

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TPrefab_SM_Pro_SmallTow_2_0.TPrefab_SM_Pro_SmallTow_2_0_C
// 0x0000 (0x02B8 - 0x02B8)
class TPrefab_SM_Pro_SmallTow_2_0::ATPrefab_SM_Pro_SmallTow_2_0_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass TPrefab_SM_Pro_SmallTow_2_0.TPrefab_SM_Pro_SmallTow_2_0_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TPrefab_SM_Pro_SmallTow_2_0_C")
	}
	static class TPrefab_SM_Pro_SmallTow_2_0::ATPrefab_SM_Pro_SmallTow_2_0_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<TPrefab_SM_Pro_SmallTow_2_0::ATPrefab_SM_Pro_SmallTow_2_0_C>();
	}
};
DUMPER7_ASSERTS_TPrefab_SM_Pro_SmallTow_2_0__ATPrefab_SM_Pro_SmallTow_2_0_C;

}

