#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateWeaponHang

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "TsAnimNotifyStateBase_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateWeaponHang.TsAnimNotifyStateWeaponHang_C
// 0x0030 (0x0088 - 0x0058)
class UTsAnimNotifyStateWeaponHang_C final : public UTsAnimNotifyStateBase_C
{
public:
	int32                                         Id;                                                // 0x0058(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           新的挂载点名;                                      // 0x0060(0x0010)(Edit, BlueprintVisible)
	TArray<struct FTransform>                     挂载相对位置;                                      // 0x0070(0x0010)(Edit, BlueprintVisible)
	int32                                         结束后状态;                                        // 0x0080(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         缓冲时间;                                          // 0x0084(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyStateWeaponHang_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyStateWeaponHang_C")
	}
	static class UTsAnimNotifyStateWeaponHang_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateWeaponHang_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyStateWeaponHang_C;

}

