#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateTimeStopRequest

#include "Basic.hpp"

#include "KuroRenderingRuntimeBPPlugin_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateTimeStopRequest.TsAnimNotifyStateTimeStopRequest_C
// 0x0000 (0x0048 - 0x0048)
class UTsAnimNotifyStateTimeStopRequest_C final : public UKuroAnimNotifyState
{
public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyStateTimeStopRequest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyStateTimeStopRequest_C")
	}
	static class UTsAnimNotifyStateTimeStopRequest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateTimeStopRequest_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyStateTimeStopRequest_C;

}

