#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsAnimNotifyStateSetMovementMode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TsAnimNotifyStateBase_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsAnimNotifyStateSetMovementMode.TsAnimNotifyStateSetMovementMode_C
// 0x0010 (0x0068 - 0x0058)
class UTsAnimNotifyStateSetMovementMode_C final : public UTsAnimNotifyStateBase_C
{
public:
	EMovementMode                                 EnterMode;                                         // 0x0058(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	EMovementMode                                 LeaveMode;                                         // 0x0059(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	uint8                                         Pad_5A[0x2];                                       // 0x005A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         EnterCustomMode;                                   // 0x005C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	int32                                         LeaveCustomMode;                                   // 0x0060(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool K2_NotifyBegin(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, float TotalDuration);
	bool K2_NotifyEnd(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation);

	class FString GetNotifyName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsAnimNotifyStateSetMovementMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsAnimNotifyStateSetMovementMode_C")
	}
	static class UTsAnimNotifyStateSetMovementMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsAnimNotifyStateSetMovementMode_C>();
	}
};
DUMPER7_ASSERTS_UTsAnimNotifyStateSetMovementMode_C;

}

