#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TsDecoratorCheckFsmState

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// TypeScriptGeneratedClass TsDecoratorCheckFsmState.TsDecoratorCheckFsmState_C
// 0x0010 (0x00B8 - 0x00A8)
class UTsDecoratorCheckFsmState_C final : public UBTDecorator_BlueprintBase
{
public:
	class FString                                 State;                                             // 0x00A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, UObjectWrapper, HasGetValueTypeHash)

public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TsDecoratorCheckFsmState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TsDecoratorCheckFsmState_C")
	}
	static class UTsDecoratorCheckFsmState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTsDecoratorCheckFsmState_C>();
	}
};
DUMPER7_ASSERTS_UTsDecoratorCheckFsmState_C;

}

